theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Say Hey to AVR Dx
description: Learning to work with the new AVR Dx series of microcontrollers
baseurl: /test-git
